package com.mk.newsshorts.core.data.remote

import com.mk.newsshorts.core.model.deeplink.ArticleDeepLinks
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull

/**
 * The page is generated by this project's own server, so what is pinned here is
 * the shape the server writes — an `href` holding the hand-off link, with its
 * ampersands HTML-escaped because that is what an attribute requires.
 */
class SharePageResolverTest {

    private fun page(handoff: String) = """
        <!DOCTYPE html>
        <html lang="ar" dir="rtl"><head><meta property="og:title" content="x"></head>
        <body><main class="card"><h1>x</h1>
        <a class="button primary" id="open" hidden href="$handoff">فتح في التطبيق</a>
        <a class="button secondary" href="https://example.com/story">اقرأ من المصدر</a>
        </main></body></html>
    """.trimIndent()

    @Test
    fun `reads the hand-off link out of the page`() {
        val html = page(
            "newsshorts://article?url=https%3A%2F%2Fexample.com%2Fstory&amp;title=Headline" +
                "&amp;summary=Body&amp;source=Example&amp;category=general&amp;published=1700000000000&amp;src=share"
        )

        val link = ArticleDeepLinks.parse(SharePageResolver.handoffLinkIn(html))!!

        assertEquals("https://example.com/story", link.url)
        assertEquals("Headline", link.title)
        assertEquals("Body", link.summary)
        // Which is what lets a share-driven open be reported apart from a push.
        assertEquals(ArticleDeepLinks.SHARE_REFERRER, link.referrer)
    }

    /**
     * Unescaping is not cosmetic: leave the entities in and every field after
     * the first arrives as part of the one before it.
     */
    @Test
    fun `unescapes the ampersands the attribute required`() {
        val html = page("newsshorts://article?url=https%3A%2F%2Fexample.com%2Fa&amp;title=Headline")

        val extracted = SharePageResolver.handoffLinkIn(html)!!

        assertEquals(false, extracted.contains("&amp;"))
        assertEquals("Headline", ArticleDeepLinks.parse(extracted)!!.title)
    }

    /**
     * A page with no article on it — the 404 page, the legacy landing page, or
     * anything else the site serves. The caller opens the page instead.
     */
    @Test
    fun `returns null when the page carries no link`() {
        assertNull(SharePageResolver.handoffLinkIn("<html><body><h1>Not found</h1></body></html>"))
        assertNull(SharePageResolver.handoffLinkIn(""))
    }

    /** An unterminated attribute must not take the rest of the document with it. */
    @Test
    fun `returns null when the link never closes`() {
        assertNull(SharePageResolver.handoffLinkIn("<a href=newsshorts://article?url=x"))
        assertNull(
            SharePageResolver.handoffLinkIn(
                "<a href=\"newsshorts://article?url=" + "x".repeat(5000) + "\">"
            )
        )
    }
}
